### ISSUE TITLE
Doesn't compile with Zig 8.0

### ISSUE THREAD

**Issue by voltflake** [Srekel/zag#1]
```
> zig build
.\build.zig:14:67: error: array literal requires address-of operator to coerce to slice type '[]const []const u8'
    exe.addCSourceFile("external/zig_wraps/sokol.c", [_][]const u8{"-std=c99"});
                                                                  ^
.\build.zig:14:68: note: referenced here
    exe.addCSourceFile("external/zig_wraps/sokol.c", [_][]const u8{"-std=c99"});
```
Pretty sure this is easy to fix, but I'm new to ZIG and don't know how to deal with this.

**Comment by Srekel** [comment]
Hey, I don't have time to look into this now, but I believe you just have to add & first, kinda like so:

>             lib.addCSourceFile(sokol_path ++ csrc, &[_][]const u8{ "-ObjC", "-DIMPL" });

Note that sokol now has a zig binding. You can check out my more recent work to see how I've added it there. 

https://github.com/Srekel/misty-fantasy/blob/main/build.zig
